// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbi7sbZJx7RyGLpkU4M6jj90SSOGmtFHo',
    appId: '1:989261264236:web:41ec3ae4f694a3be56af49',
    messagingSenderId: '989261264236',
    projectId: 'genwise-bc358',
    authDomain: 'genwise-bc358.firebaseapp.com',
    storageBucket: 'genwise-bc358.firebasestorage.app',
    measurementId: 'G-2MHSXWCGZ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8AJQfWpgxFWP5oW_kYXQczfTVO6Ficjo',
    appId: '1:989261264236:android:780462e71ba8b0f756af49',
    messagingSenderId: '989261264236',
    projectId: 'genwise-bc358',
    storageBucket: 'genwise-bc358.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4hXi-wJCd9u_sItbYZxDHVgknGBchgzA',
    appId: '1:989261264236:ios:5ca3504fa2a0955b56af49',
    messagingSenderId: '989261264236',
    projectId: 'genwise-bc358',
    storageBucket: 'genwise-bc358.firebasestorage.app',
    iosBundleId: 'com.example.genwise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4hXi-wJCd9u_sItbYZxDHVgknGBchgzA',
    appId: '1:989261264236:ios:5ca3504fa2a0955b56af49',
    messagingSenderId: '989261264236',
    projectId: 'genwise-bc358',
    storageBucket: 'genwise-bc358.firebasestorage.app',
    iosBundleId: 'com.example.genwise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbi7sbZJx7RyGLpkU4M6jj90SSOGmtFHo',
    appId: '1:989261264236:web:8b1e389d7819679856af49',
    messagingSenderId: '989261264236',
    projectId: 'genwise-bc358',
    authDomain: 'genwise-bc358.firebaseapp.com',
    storageBucket: 'genwise-bc358.firebasestorage.app',
    measurementId: 'G-2YDD0778GN',
  );
}
